// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIu2zNbOR0QE36ENaF5N68hwHm731-eQ',
    appId: '1:672829626861:web:8c9c4511d67a3f57c96fe4',
    messagingSenderId: '672829626861',
    projectId: 'gpbl-40988',
    authDomain: 'gpbl-40988.firebaseapp.com',
    databaseURL: 'https://gpbl-40988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpbl-40988.firebasestorage.app',
    measurementId: 'G-TP7ZLD085Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-OOKh7T2TBE94vTladoPQaWhKFfI4FQ',
    appId: '1:672829626861:android:637dd8b9909f69c0c96fe4',
    messagingSenderId: '672829626861',
    projectId: 'gpbl-40988',
    databaseURL: 'https://gpbl-40988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpbl-40988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDteeP3FIoRTRNxhR8BGSsMmLXGPY4f2Ak',
    appId: '1:672829626861:ios:61202981e59b141fc96fe4',
    messagingSenderId: '672829626861',
    projectId: 'gpbl-40988',
    databaseURL: 'https://gpbl-40988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpbl-40988.firebasestorage.app',
    iosBundleId: 'com.example.gpbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDteeP3FIoRTRNxhR8BGSsMmLXGPY4f2Ak',
    appId: '1:672829626861:ios:61202981e59b141fc96fe4',
    messagingSenderId: '672829626861',
    projectId: 'gpbl-40988',
    databaseURL: 'https://gpbl-40988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpbl-40988.firebasestorage.app',
    iosBundleId: 'com.example.gpbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCIu2zNbOR0QE36ENaF5N68hwHm731-eQ',
    appId: '1:672829626861:web:8ae112d783b6b214c96fe4',
    messagingSenderId: '672829626861',
    projectId: 'gpbl-40988',
    authDomain: 'gpbl-40988.firebaseapp.com',
    databaseURL: 'https://gpbl-40988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gpbl-40988.firebasestorage.app',
    measurementId: 'G-S0MP0203TF',
  );
}
